#!/bin/bash

# The commands provided here will be executed for building the documentation in the ci
# but may also be used locally

pip install myst-parser # workaround. Should be included in Docker image?
pip install -e .
sphinx-apidoc -f -o docs/sphinx src/pymrm
if [[ "${CI}" == "true" ]]; then
    if ! git diff --quiet -- docs/sphinx/pymrm.rst docs/sphinx/modules.rst; then
        echo "Detected outdated autogenerated Sphinx API files:"
        git --no-pager diff -- docs/sphinx/pymrm.rst docs/sphinx/modules.rst
        echo "Run 'sphinx-apidoc -f -o docs/sphinx src/pymrm' and commit the updated rst files."
        exit 1
    fi
fi
cd docs/sphinx
mkdir -p _static
make html 2>documentation_errors.txt
num_warnings=$(wc -l < documentation_errors.txt)
echo "Found $num_warnings problem(s) during sphinx-build"
if [[ $num_warnings -gt 1 ]]; then
    echo Sphinx documentation needs to be improved!
    exit 1
fi
echo Sphinx documentation was build successfully
